services:
  wiremock:
    image: wiremock/wiremock:3.7.0
    ports:
      - "8080:8080"
    command: [ "--verbose" ]
  smtp:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
