services:
  wiremock:
    image: sheyenrath/wiremock.net
    ports:
      - "8080:80"
    command: [ "--verbose" ]
  smtp:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
