<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Itselves.AlertManager.Telegram</Title>
    <PackageTags>alert manager alertmanager telegram</PackageTags>
    <Description>Library for alert manager which use Telegram bot as a provider</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/maximiliysiss/itselves.alertmanager/tree/master/src/Itselves.AlertManager.Telegram</PackageProjectUrl>
    <RepositoryUrl>https://github.com/maximiliysiss/itselves.alertmanager/tree/master/src/Itselves.AlertManager.Telegram</RepositoryUrl>
    <PackageId>Itselves.AlertManager.Telegram</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Itselves.AlertManager.Abstraction\Itselves.AlertManager.Abstraction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Telegram.Bot" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
